name: Update gist with Date

on:
    schedule:
        - cron: "0 0 * * *"
    # Manual triggers with workflow_dispatch
    workflow_dispatch:

jobs:
    update-gist:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Update gist
              uses: kf-liu/date-box@master
              env:
                  TYPE: DAY
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  GIST_ID: 34e7077ab418a9106d19d5bae73523da
                  RECORDS: "0 * * * 0,6 _ WEEKEND | 0 * 22 12 * _ MY BIRTHDAY"
